feeds/urls.py
"""
Urls for feeds app.
"""
from django.urls import path
from feeds.views import FeedCreate, FeedList

app_name = "feeds"
urlpatterns = [
    path("", FeedList.as_view(), name="home"),
    path("create/", FeedCreate.as_view(), name="create"),
]

questions/urls.py
"""
Urls for questions app.
"""
from django.urls import path
from .views import (
    AnswerCreate,
    AnswerEdit,
    QuestionCreate,
    QuestionEdit,
    QuestionDetail,
    QuestionList,
)

app_name = "questions"
urlpatterns = [
    path("", QuestionList.as_view(), name="home"),
    path("create/", QuestionCreate.as_view(), name="create"),
    path("<uuid:pk>/edit/", QuestionEdit.as_view(), name="edit"),
    path("<uuid:pk>/", QuestionDetail.as_view(), name="detail"),
    path("<uuid:pk>/answer/", AnswerCreate.as_view(), name="answer"),
    path(
        "<uuid:question_pk>/answers/<uuid:pk>/edit/",
        AnswerEdit.as_view(),
        name="answer_edit",
    ),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import Follow, Login, Network, Profile, SignUp, Unfollow

app_name = "users"
urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<uuid:pk>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/<str:category>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/follow", Follow.as_view(), name="follow"),
    path("<uuid:pk>/unfollow", Unfollow.as_view(), name="unfollow"),
    path("network/<str:filter>/", Network.as_view(), name="network"),
]

questions/models.py
"""
Models for questions app.
"""
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from core.models import TimeStampedModel


class Question(TimeStampedModel):
    """
    Model class for questions.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    description = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="questions"
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns absolute url of question.
        """
        return reverse("questions:detail", args=[self.pk])


class Answer(TimeStampedModel):
    """
    Model class for answers.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField()
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="answers"
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.text[:100]

    def get_absolute_url(self):
        """
        Returns absolute url of answer.
        """
        return reverse("questions:detail", args=[self.question.pk])

questions/forms.py
"""
Forms for questions app.
"""
from django import forms
from questions.models import Answer, Question


class QuestionModelForm(forms.ModelForm):
    """
    Model form class for Question model.
    """

    class Meta:
        model = Question
        fields = ("title", "description")

    def save(self, author=None, commit=True):
        if author:
            self.instance.author = author
        if commit:
            self.instance.save()
        return self.instance


class AnswerModelForm(forms.ModelForm):
    """
    Model form class for Answer model.
    """

    class Meta:
        model = Answer
        fields = ("text",)

    def save(self, question=None, author=None, commit=True):
        if question:
            self.instance.question = question
        if author:
            self.instance.author = author
        if commit:
            self.instance.save()
        return self.instance

questions/views.py
"""
Views for questions app.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from questions.forms import AnswerModelForm, QuestionModelForm
from questions.models import Answer, Question


class QuestionList(generic.ListView):
    """
    View class for listing questions.
    """

    queryset = Question.objects.all()
    paginate_by = 10
    context_object_name = "questions"


class QuestionCreate(LoginRequiredMixin, generic.CreateView):
    """
    View class for creating questions.
    """

    queryset = Question.objects.all()
    form_class = QuestionModelForm
    template_name = "questions/question_create.html"

    def form_valid(self, form):
        question = form.save(author=self.request.user)
        return redirect(question)


class QuestionEdit(LoginRequiredMixin, generic.UpdateView):
    """
    View class for editing questions.
    """

    queryset = Question.objects.all()
    form_class = QuestionModelForm
    template_name = "questions/question_create.html"


class QuestionDetail(generic.DetailView):
    """
    View class for viewing a single question.
    """

    queryset = Question.objects.all()


class AnswerCreate(LoginRequiredMixin, generic.CreateView):
    """
    View class for creating answers.
    """

    queryset = Answer.objects.all()
    form_class = AnswerModelForm
    template_name = "questions/answer_create.html"

    def form_valid(self, form):
        question = get_object_or_404(Question, pk=self.kwargs["pk"])
        form.save(question=question, author=self.request.user)
        return redirect(question)


class AnswerEdit(LoginRequiredMixin, generic.UpdateView):
    """
    View class for editing answers.
    """

    queryset = Answer.objects.all()
    form_class = AnswerModelForm
    template_name = "questions/answer_create.html"

templates/questions/_answer_list.html
{% load humanize %}

<ul id="answer_list">
    {% for answer in answers %}
    <li id="{{ answer.pk }}" class="answer_item">
        <a href="{{ answer.author.get_absolute_url }}"><strong>{{ answer.author }}</strong></a>
        wrote {{ answer.created_at|naturaltime }}:
        {% if request.user == answer.author %}
        <a href="{% url 'questions:answer_edit' answer.question.pk answer.pk %}">Edit</a>
        {% endif %}
        <p>
            <a href="{% url 'questions:detail' answer.question.pk %}#{{ answer.pk }}">{{ answer.text|linebreaksbr }}</a>
        </p>
    </li>
    {% endfor %}
</ul>

templates/questions/_question_list.html
{% load humanize %}


<ul id="question_list">
    {% for question in questions %}
    <li class="question_item">
        <h4>
            <a href="{{ question.get_absolute_url }}">{{ question }}</a>
        </h4>
        - by
        <a href="{{ question.author.get_absolute_url }}"><strong>{{ question.author }}</strong></a>
        {{ question.created_at|naturaltime }}
    </li>
    {% endfor %}
</ul>

templates/questions/answer_create.html
{% extends 'base.html' %}

{% block main %}
<form method="POST" name="answer_form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="Submit">
</form>
{% endblock %}

templates/questions/question_create.html
{% extends 'base.html' %}

{% block main %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="Submit">
  <a href="{% url 'questions:home' %}">Cancel</a>
</form>
{% endblock %}

templates/questions/question_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block main %}
{% if question %}
<h4>{{ question.title }}</h4>
{% if request.user == question.author %}
<a href="{% url 'questions:edit' question.pk %}">Edit</a>
{% endif %}
<br>
Author - <a href="{{ question.author.get_absolute_url }}"><strong>{{ question.author }}</strong></a>
<br>
Created - {{ question.created_at|naturaltime }}
<p>{{ question.description|linebreaksbr }}</p>
<a href="{% url 'questions:answer' question.pk %}"><strong>Answer it</strong></a>
{% if question.answers %}
{% include 'questions/_answer_list.html' with answers=question.answers.all %}
{% else %}
<p><strong>No Answers</strong></p>
{% endif %}
{% endif %}
{% endblock %}

templates/questions/question_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block main %}
{% if user.is_authenticated %}
<a href="{% url 'questions:create' %}">Ask a question</a>
{% else %}
<a href="{% url 'users:login' %}?next={{ request.get_full_path}}"><strong>Login</strong></a> to ask a question
{% endif %}
{% if questions %}
{% include 'questions/_question_list.html' with questions=questions %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% else %}
<p><strong>No Questions</strong></p>
{% endif %}
{% endblock %}