articles/urls.py
from django.urls import path
from .views import ArticleCreate, ArticleDetail, ArticleEdit, ArticleList, DraftList

app_name = "articles"
urlpatterns = [
    path("", ArticleList.as_view(), name="home"),
    path("<uuid:pk>/", ArticleDetail.as_view(), name="detail"),
    path("create/", ArticleCreate.as_view(), name="create"),
    path("drafts/", DraftList.as_view(), name="drafts"),
    path("<uuid:pk>/edit/", ArticleEdit.as_view(), name="edit"),
]

feeds/urls.py
"""
Urls for feeds app.
"""
from django.urls import path
from feeds.views import FeedCreate, FeedList

app_name = "feeds"
urlpatterns = [
    path("", FeedList.as_view(), name="home"),
    path("create/", FeedCreate.as_view(), name="create"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import Follow, Login, Network, Profile, SignUp, Unfollow

app_name = "users"
urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<uuid:pk>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/<str:category>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/follow", Follow.as_view(), name="follow"),
    path("<uuid:pk>/unfollow", Unfollow.as_view(), name="unfollow"),
    path("network/<str:filter>/", Network.as_view(), name="network"),
]

articles/models.py
"""
Models for articles app.
"""
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from core.models import TimeStampedModel


class Article(TimeStampedModel):
    """
    Class for article model.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    text = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles"
    )
    published_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns the absolute url of article.
        """
        return reverse("articles:detail", args=[self.pk])

    def publish(self):
        """
        Adds a publishing date and time to the article.
        """
        self.published_at = timezone.now()
        self.save()

    @property
    def published(self):
        """
        Returns whether article is published or not.
        """
        return self.published_at is not None

articles/forms.py
"""
Forms for articles app.
"""
from django import forms
from .models import Article


class ArticleModelForm(forms.ModelForm):
    """
    Form class for articles.
    """

    class Meta:
        model = Article
        fields = (
            "title",
            "text",
        )

    def save(self, author=None, commit=True):
        if author:
            self.instance.author = author
        if commit:
            self.instance.save()
        return self.instance

articles/views.py
"""
Views for articles app.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, reverse
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from .forms import ArticleModelForm
from .models import Article


class ArticleList(ListView):
    """
    View class for listing articles.
    """

    queryset = Article.objects.exclude(published_at=None)
    paginate_by = 10
    context_object_name = "articles"


class ArticleCreate(LoginRequiredMixin, CreateView):
    """
    View class for creating articles.
    """

    queryset = Article.objects.all()
    form_class = ArticleModelForm
    template_name = "articles/article_create.html"

    def form_valid(self, form):
        article = form.save(author=self.request.user)
        if "publish" in self.request.POST:
            article.publish()
        return redirect(article)


class ArticleEdit(UpdateView):
    """
    View class for editing articles.
    """

    queryset = Article.objects.all()
    form_class = ArticleModelForm
    template_name = "articles/article_create.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("users:login"))
        if self.get_object().author != request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        article = form.save()
        if "publish" in self.request.POST:
            article.publish()
        return redirect(article)


class ArticleDetail(DetailView):
    """
    View class for single article.
    """

    queryset = Article.objects.all()


class DraftList(LoginRequiredMixin, ListView):
    """
    View class for logged-in user's drafts.
    """

    paginate_by = 10
    context_object_name = "articles"

    def get_queryset(self):
        return Article.objects.filter(author=self.request.user).filter(
            published_at=None
        )

templates/articles/_article_list.html
{% load humanize %}

<ul id="article_list">
    {% for article in articles %}
    <li class="article_item">
        <h4>
            <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
        </h4>
        - by <a href="{{ article.author.get_absolute_url }}"><strong>{{ article.author }}</strong></a>
        {{ article.created_at|naturaltime }}
    </li>
    {% endfor %}
</ul>

templates/articles/article_create.html
{% extends 'base.html' %}

{% block main %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  {% if object.published %}
  <input type="submit" name="update" value="Update">
  <a href="{% url 'articles:detail' object.pk %}">Cancel</a>
  {% else %}
  <input type="submit" name="publish" value="Publish">
  <input type="submit" name="draft" value="Save as draft">
  <a href="{% url 'articles:home' %}">Cancel</a>
  {% endif %}
</form>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block main %}
{% if article %}
<h3>{{ article.title }}</h3>
{% if request.user == article.author %}
<a href="{% url 'articles:edit' article.pk %}">Edit</a>
{% endif %}
<br>
Author - <a href="{{ article.author.get_absolute_url }}"><strong>{{ article.author }}</strong></a>
<br>
{% if article.published %}
Published at: {{ article.published_at|naturaltime }}
{% else %}
<strong>Not published</strong>
{% endif %}
<p>{{ article.text|linebreaksbr }}</p>
{% endif %}
{% endblock %}

templates/articles/article_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block main %}
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">Create a new article</a>
<a href="{% url 'articles:drafts' %}">My drafts</a>
{% else %}
<a href="{% url 'users:login' %}?next={{ request.get_full_path}}"><strong>Login</strong></a> to add an article
{% endif %}
{% if articles %}
{% include 'articles/_article_list.html' with articles=articles %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% else %}
<p><strong>No Articles</strong></p>
{% endif %}
{% endblock %}