articles/urls.py
from django.urls import path
from .views import ArticleCreate, ArticleDetail, ArticleEdit, ArticleList, DraftList

app_name = "articles"
urlpatterns = [
    path("", ArticleList.as_view(), name="home"),
    path("<uuid:pk>/", ArticleDetail.as_view(), name="detail"),
    path("create/", ArticleCreate.as_view(), name="create"),
    path("drafts/", DraftList.as_view(), name="drafts"),
    path("<uuid:pk>/edit/", ArticleEdit.as_view(), name="edit"),
]

feeds/urls.py
"""
Urls for feeds app.
"""
from django.urls import path
from feeds.views import FeedCreate, FeedList

app_name = "feeds"
urlpatterns = [
    path("", FeedList.as_view(), name="home"),
    path("create/", FeedCreate.as_view(), name="create"),
]

polls/urls.py
"""
Urls for polls app.
"""
from django.urls import path
from polls.views import PollCreate, PollDetail, PollList, vote

app_name = "polls"
urlpatterns = [
    path("", PollList.as_view(), name="home"),
    path("create/", PollCreate.as_view(), name="create"),
    path("<uuid:pk>/", PollDetail.as_view(), name="detail"),
    path("<uuid:pk>/vote", vote, name="vote"),
]

search/urls.py
"""
URLs for search app.
"""
from django.urls import path
from .views import Search

app_name = "search"
urlpatterns = [
    path("", Search.as_view(), name="home"),
    path("<str:category>/", Search.as_view(), name="home"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import Follow, Login, Network, Profile, SignUp, Unfollow

app_name = "users"
urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<uuid:pk>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/<str:category>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/follow", Follow.as_view(), name="follow"),
    path("<uuid:pk>/unfollow", Unfollow.as_view(), name="unfollow"),
    path("network/<str:filter>/", Network.as_view(), name="network"),
]

templates/base.html
{% load static %}
<html>

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}" />
  <title>{% block title %}Bootcamp{% endblock %}</title>
</head>

<body>
  {% block header %}
  <header>
    <div class="left">
      <a href="{% url 'home' %}"><span class="home">BootCamp</span></a>
      <a href="{% url 'feeds:home' %}">Feeds</a>
      <a href="{% url 'articles:home' %}">Articles</a>
      <a href="{% url 'questions:home' %}">Questions</a>
      <a href="{% url 'polls:home' %}">Polls</a>
      <a href="{% url 'users:network' 'users' %}">Network</a>
      <a href="{% url 'search:home' %}">Search</a>
    </div>
    <div class="right">
      {% if request.user.is_authenticated %}
      <a href="{% url 'users:profile' request.user.pk %}">{{ request.user.name }}</a>
      <a href="{% url 'users:logout' %}?next={{ request.get_full_path}}">Logout</a>
      {% else %}
      <a href="{% url 'users:login' %}?next={{ request.get_full_path}}">Login</a>
      <a href="{% url 'users:signup' %}">Signup</a>
      {% endif %}
    </div>
  </header>
  {% endblock %}
  <main>{% block main %} {% endblock %}</main>

  <script src="{% static 'scripts/jquery-3.5.1.js' %}"></script>
  <script src="{% static 'scripts/base.js' %}"></script>
</body>

</html>