articles/urls.py
from django.urls import path
from .views import ArticleCreate, ArticleDetail, ArticleEdit, ArticleList, DraftList

app_name = "articles"
urlpatterns = [
    path("", ArticleList.as_view(), name="home"),
    path("<uuid:pk>/", ArticleDetail.as_view(), name="detail"),
    path("create/", ArticleCreate.as_view(), name="create"),
    path("drafts/", DraftList.as_view(), name="drafts"),
    path("<uuid:pk>/edit/", ArticleEdit.as_view(), name="edit"),
]

feeds/urls.py
"""
Urls for feeds app.
"""
from django.urls import path
from feeds.views import FeedCreate, FeedList

app_name = "feeds"
urlpatterns = [
    path("", FeedList.as_view(), name="home"),
    path("create/", FeedCreate.as_view(), name="create"),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import Follow, Login, Network, Profile, SignUp, Unfollow

app_name = "users"
urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<uuid:pk>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/<str:category>/", Profile.as_view(), name="profile"),
    path("<uuid:pk>/follow", Follow.as_view(), name="follow"),
    path("<uuid:pk>/unfollow", Unfollow.as_view(), name="unfollow"),
    path("network/<str:filter>/", Network.as_view(), name="network"),
]

users/models.py
"""
Contains the User model class
"""
import uuid
from django.contrib import auth
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import gettext_lazy as _


class UserManager(BaseUserManager):
    """
    Manager class for User model.
    """

    use_in_migrations = True

    def _create_user(self, name, email, password, **extra_fields):
        """
        Create and save a user with given name, email and password.
        """
        if not email:
            raise ValueError(_("Users must have an email address"))

        if not name:
            raise ValueError(_("Users must have a name"))

        email = self.normalize_email(email)
        user = self.model(name=name, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, name, email, password=None, **extra_fields):
        """
        Create and save a user with given name, email and password.
        """
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(name, email, password, **extra_fields)

    def create_superuser(self, name, email, password=None, **extra_fields):
        """
        Create and save a superuser with given name, email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(name, email, password, **extra_fields)

    def with_perm(
        self, perm, is_active=True, include_superusers=True, backend=None, obj=None
    ):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    "You have multiple authentication backends configured and "
                    "therefore must provide the `backend` argument."
                )
        elif not isinstance(backend, str):
            raise TypeError(
                "backend must be a dotted import path string (got %r)." % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, "with_perm"):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    A class defining the user model
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(
        _("email address"),
        unique=True,
        error_messages={
            "unique": _("A user with that email already exists."),
        },
    )
    name = models.CharField(_("name"), max_length=255)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    followers = models.ManyToManyField(
        "self", related_name="followees", symmetrical=False, through="Followership"
    )

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ("name",)

    objects = UserManager()

    class Meta:
        ordering = ["name"]
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url of the object.
        """
        return reverse("users:profile", args=[self.id])

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the name of the user.
        """
        return self.name

    def get_short_name(self):
        """
        Return the name for the user.
        """
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def follow(self, user=None):
        """
        Add the user as follower.
        """
        if user is not None:
            self.followers.add(user)
            self.save()

    def unfollow(self, user=None):
        """
        Removes the user as follower.
        """
        if user is not None:
            self.followers.remove(user)
            self.save()


class Followership(models.Model):
    """
    Defines a followership between two entities.
    """

    followee = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="followers_followerships"
    )
    follower = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="followees_followerships"
    )
    start_date = models.DateTimeField(auto_now_add=True)

users/forms.py
"""
Contains form classes for User model.
"""
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.core.exceptions import ValidationError
from django.utils.text import gettext_lazy as _
from .models import User


class UserCreationForm(forms.ModelForm):
    """
    Form class for creating a user.
    """

    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = (
            "name",
            "email",
            "password",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs[
                "autofocus"
            ] = True

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get("password")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password", error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(BaseUserChangeForm):
    """
    A form for changing user information in admin interface.
    """

    class Meta:
        model = User
        fields = "__all__"

users/views.py
"""
Contains views for users app.
"""
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, redirect_to_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic, View
from articles.models import Article
from feeds.models import Feed
from polls.models import Question as Poll
from questions.models import Question, Answer
from users.forms import UserCreationForm
from users.models import User


class SignUp(generic.CreateView):
    """
    View class for signing up a user.
    """

    queryset = User.objects.all()
    form_class = UserCreationForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("users:login")


class Login(LoginView):
    """
    View class for logging in a user.
    """

    template_name = "users/login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)


class Profile(generic.ListView):
    """
    View class for user profile.
    """

    template_name = "users/profile.html"
    context_object_name = "posts"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        user = get_object_or_404(User, pk=self.kwargs["pk"])
        context_data["user"] = user
        if "category" in self.kwargs:
            context_data["category"] = self.kwargs["category"]
        else:
            context_data["category"] = "feeds"
        return context_data

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs["pk"])
        if "category" in self.kwargs:
            category = self.kwargs["category"]
            if category == "feeds" or category == "":
                posts = Feed.objects.filter(author=user)
            elif category == "articles":
                posts = Article.objects.filter(author=user).exclude(published_at=None)
            elif category == "questions":
                posts = Question.objects.filter(author=user)
            elif category == "answers":
                posts = Answer.objects.filter(author=user)
            elif category == "polls":
                posts = Poll.objects.filter(author=user)
            else:
                posts = []
        else:
            posts = Feed.objects.filter(author=user)
        return posts


class Follow(LoginRequiredMixin, View):
    """
    View class for following users.
    """

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs["pk"])
        if user != request.user:
            user.follow(request.user)
        return redirect(user)


class Unfollow(LoginRequiredMixin, View):
    """
    View class for unfollowing users.
    """

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs["pk"])
        if user != request.user:
            user.unfollow(request.user)
        return redirect(user)


class Network(generic.ListView):
    """
    View class for listing folllowers and followees.
    """

    queryset = User.objects.all()
    template_name = "users/network.html"
    paginate_by = 10
    context_object_name = "users"

    def dispatch(self, request, *args, **kwargs):
        if kwargs["filter"] != "users" and request.user.is_anonymous:
            return redirect_to_login(
                request.get_full_path(),
            )
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        users = User.objects.all()
        if self.kwargs["filter"] == "followers":
            users = users.filter(id__in=self.request.user.followers.all())
        if self.kwargs["filter"] == "followees":
            users = users.filter(id__in=self.request.user.followees.all())
        return users

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["filter"] = self.kwargs["filter"]
        return context_data

templates/users/_user_list.html
<ul id="user_list">
    {% for user in users %}
    <li class="user_item">
        <a href="{% url 'users:profile' user.pk %}">{{ user }}</a>
    </li>
    {% endfor %}
</ul>

templates/users/login.html
{% extends "base.html" %}

{% block main %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" name="login_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" name="submit" value="Login">
<input type="hidden" name="next" value="{{ next }}">
If you are new, <a href="{% url 'users:signup' %}">Signup</a>
</form>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}

templates/users/network.html
{% extends 'base.html' %}

{% block main %}
<a href="{% url 'users:network' 'users' %}"><strong>Users</strong></a>
{% if request.user.is_authenticated %}
<a href="{% url 'users:network' 'followers' %}"><strong>Followers</strong></a>
<a href="{% url 'users:network' 'followees' %}"><strong>Followees</strong></a>
{% endif %}
<h2>{{ filter|capfirst }}</h2>
{% if users %}
{% include 'users/_user_list.html' with users=users %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% else %}
<strong>No {{ filter|capfirst }}</strong>
{% endif %}
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load humanize %}

{% block main %}
<h2>{{ user }}</h2>
{% if user != request.user %}
{% if request.user in user.followers.all %}
<a href="{% url 'users:unfollow' user.pk %}">unfollow</a>
{% else %}
<a href="{% url 'users:follow' user.pk %}">follow</a>
{% endif %}
{% endif %}
<table id="user_activity">
    <caption>A count of all the activities of {{ user }}.</caption>
    <thead>
        <tr>
            <th scope="col">
                <a href="{% url 'users:profile' user.pk 'feeds' %}">Feeds</a>
            </th>
            <th scope="col">
                <a href="{% url 'users:profile' user.pk 'articles' %}">Articles</a>
            </th>
            <th scope="col">
                <a href="{% url 'users:profile' user.pk 'questions' %}">Questions</a>
            </th>
            <th scope="col">
                <a href="{% url 'users:profile' user.pk 'answers' %}">Answers</a>
            </th>
            <th scope="col">
                <a href="{% url 'users:profile' user.pk 'polls' %}">Polls</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ user.feeds.count }}</td>
            <td>{{ user.articles.count }}</td>
            <td>{{ user.questions.count }}</td>
            <td>{{ user.answers.count }}</td>
            <td>{{ user.polls.count }}</td>
        </tr>
    </tbody>
</table>
<h2>
    {{ category|capfirst }}
</h2>
<h4>
    {% if request.user == user and category == 'articles' %}
    view your <a href="{% url 'articles:drafts' %}">drafts</a>
    {% endif %}
</h4>
{% if posts %}
{% if category == 'feeds' %}
{% include 'feeds/_feed_list.html' with feeds=posts %}
{% elif category == 'articles' %}
{% include 'articles/_article_list.html' with articles=posts %}
{% elif category == 'questions' %}
{% include 'questions/_question_list.html' with questions=posts %}
{% elif category == 'answers' %}
{% include 'questions/_answer_list.html' with answers=posts %}
{% elif category == 'polls' %}
{% include 'polls/_poll_list.html' with polls=posts %}
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last
            &raquo;</a>
        {% endif %}
    </span>
</div>
{% else %}
<strong>No {{ category|capfirst }}</strong>
{% endif %}
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block title %}
Bootcamp - Signup
{% endblock %}

{% block main %}
<form method='POST' name="signup_form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' name='submit' value='Signup'>
    If you have an account, <a href="{% url 'users:login' %}">Login</a>
</form>
{% endblock %}